### ISSUE TITLE
Change name of package

### ISSUE THREAD

**Issue by seandavi** [seandavi/MicroBioMap#11]
Any suggestions?

**Comment by cgreene** [comment]
bugdata.org!

**Comment by rabdill** [comment]
My preference is also for bugdata.org—it's short, memorable, and punny, plus it's broad enough that it will still make sense if we add more body sites or assays. I also think "bugdata" is a delightful name for an R package. In addition to Ran's suggestion, `microbiomecompendium.org`, here are some alternatives that aren't registered yet:
* commensals.org
* ourmicrobes.org
* 16Sdata.org
* ourmicrobio.me
   * probably too similar to `microbio.me`?
* bugcensus.org
   * (And/or bugcens.us if we're feeling cute)
* gutflorist.org
* bodybugs.org
* tinyfriends.org

**Comment by rabdill** [comment]
For what it's worth, `microbiomap.org` is available and doesn't seem like a bad option either—we're not really offering a "map" in the conventional sense I guess, but it does suggest a global scope and doesn't rule out adding other body sites later.

**Comment by seandavi** [comment]
Not sure if these are available, but an LLM recommended:

- microbe.world
- microbes.io
- tinylife.data
- bugbase.net
- microbesamples.org
- freemicrodata.com
- openmicrobiome.org
- microbedb.com
- microbesamples.net
- microworld.org
- bacteriabase.com
- microbedata.org
- thebugbox.com
- germbank.net
- microbes.net
- micromedatabase.org

**Comment by rabdill** [comment]
Checking with Cloudflare's registrar, it looks like these are the ones we could use:
> * ~microbe.world~
> * ~microbes.io~
> * ~tinylife.data~
> * ~bugbase.net~
> * microbesamples.org
> * freemicrodata.com
> * ~openmicrobiome.org~
> * ~microbedb.com~
> * microbesamples.net
> * ~microworld.org~
> * bacteriabase.com
> * microbedata.org
> * ~thebugbox.com~
> * germbank.net
> * ~microbes.net~
> * micromedatabase.org

**Comment by cgreene** [comment]
I really wish thebugbox.com was a subscription site that sent you GitHub issues handwritten on artisanal paper every month!

**Comment by seandavi** [comment]
The consensus is to stick with MicroBioMap. The website name (now registered) is https://microbiomap.org.
